app/components/swap-row.tsx, app/components/swap-table.tsx, app/types/global.ts
https://app.asana.com/0/1201981556336821/1202026037311640
=> Removes native currency toggle

app/components/swap-table.tsx, app/connectors/index.ts, app/hooks/use-on-supported-network.ts
REF: https://app.asana.com/0/1201981556336821/1202073815846714
=> Shows warnning message when joined on unsupported network

app/components/connect-wallet.tsx
REF: https://app.asana.com/0/1201981556336821/1202132817046461
=> Fixes double connect error message

app/components/borrow-flow/borrow.tsx, app/components/borrow-flow/repay.tsx, app/components/deposit-flow/deposit.tsx, app/components/deposit-flow/withdraw.tsx
=> Use the token icon on the APYs

app/components/swap-table.tsx, app/hooks/use-on-supported-network.ts
REF: https://app.asana.com/0/1201981556336821/1202027298813808
=> Better error handling for unsupported network

app/components/borrow-flow.tsx, app/components/borrow-flow/borrow.tsx, app/components/borrow-flow/repay.tsx, app/components/deposit-flow/deposit.tsx, app/components/deposit-flow/withdraw.tsx, app/components/max.tsx, tailwind.config.js
=> Max button

app/components/borrow-flow/borrow.tsx, app/components/borrow-flow/repay.tsx, app/components/deposit-flow/deposit.tsx, app/components/deposit-flow/withdraw.tsx
=> Hides distribution APY and styles

.gitignore, app/components/borrow-flow/borrow.tsx, app/components/borrow-flow/repay.tsx, app/components/deposit-flow/deposit.tsx, app/components/deposit-flow/withdraw.tsx, app/hooks/use-valid-input.ts
completes https://app.asana.com/0/home/1201981678382625/1202157876577868
=> Disable invalid transactions

app/components/borrow-flow/borrow.tsx, app/components/borrow-flow/repay.tsx, app/components/deposit-flow/deposit.tsx, app/components/deposit-flow/withdraw.tsx
https://app.asana.com/0/1201981556336821/1202132880667536
=> Hides borrow limit used if nothing borrowed yet

app/components/swap-table.tsx
Introduced here: https://github.com/tender-finance/tender-frontend/pull/32
We need to clean up the token/config logic to avoid problems like this in the future.
=> [regression] corrects token lookup

app/components/borrow-flow/borrow.tsx, app/components/borrow-flow/repay.tsx, app/components/deposit-flow/deposit.tsx, app/components/deposit-flow/withdraw.tsx, app/components/fi-modal/confirming-transition.tsx, app/lib/tender.ts, package-lock.json, package.json
REF: https://app.asana.com/0/1201981556336821/1202177416272959
The diffs here are deceptively large.
What happens:
1. Extra top level conditional of all deposity/borrow components that shows waiting screen if transaction in flight
2. All `tender.ts` function return the transaction so we can `txn.wait()`
3. User can close the waiting modal optimistically
As a follow up task we need to handle the failure states from the transaction.
=> Confirm transaction before autoclose modal

app/components/borrow-flow.tsx, app/hooks/use-borrowed-amount.ts, app/lib/apy-calculations.ts, app/lib/tender.ts
Two functions we need for the top part
=> getTotalSupplied && netApy function

app/components/account-summary.tsx, app/components/swap-table.tsx, app/contexts/tender-context.ts, app/hooks/use-net-apy.ts, app/hooks/use-network-data.ts, app/hooks/use-tender-context.ts, app/hooks/use-token-pairs.ts, app/hooks/use-total-supply-balance-in-usd.ts, app/lib/apy-calculations.ts, app/lib/tender.ts, app/routes/app.tsx, app/types/global.ts
This PR under-rides the changes we're making here: https://app.asana.com/0/1201981556336821/1202192875770857
=> Expose Tender Provider for app wide data

app/components/account-summary.tsx, app/components/account-summary/ring.tsx, app/components/connect-wallet.tsx, app/components/two-panes.tsx
`green % = (total supply) / (total supply + total borrow)`
=> Circle Animation around netapy

app/components/Header.tsx, app/components/account-summary.tsx, app/components/borrow-flow/repay.tsx, app/components/deposit-flow/deposit.tsx, app/components/two-panes/market-borrow-row.tsx, app/components/two-panes/market-supply-row.tsx, app/hooks/use-markets.ts, app/hooks/use-tender-context.ts, app/types/global.ts
Ref: 
* https://app.asana.com/0/home/1201981678382625/1202233470842632
* https://app.asana.com/0/home/1201981678382625/1202233470842624
* https://app.asana.com/0/home/1201981678382625/1202233754163346
=> Approval flow

app/routes/index.tsx
=> Style enter app button on homepage the same as the others

app/components/account-summary/empty.tsx, app/components/disconnected-warning.tsx, app/root.tsx, app/routes/index.tsx
=> Zero state for wrong network

app/components/borrow-flow/borrow.tsx, app/hooks/use-valid-input.ts
=> Insufficient liquiditiy

app/components/deposit-flow/withdraw.tsx
https://app.asana.com/0/1201981556336821/1202272269075863
This is much closer to right. We are still a point or two about 100. Closer to a rounding issues here.
=> Sets max withdraw to much closer to the right number

app/hooks/use-markets.ts
Ref: https://app.asana.com/0/1201981556336821/1202233470943351
cc @mitchtrale Would you mind checking this reloads all the data you would expect after transaction?
=> Update the rest of the data on poll and transaction

app/components/account-summary/empty.tsx, app/components/disconnected-warning.tsx
@mitchtrale this is what we ran into with testing today
=> Delays network warning and keeps sizing consistent when reloading

app/config/networks/rinkeby.ts, app/lib/tender.ts
This branch lets you test the other functionality until we get the price oracle sorted out.
=> Hardcoded pricing - Comment out price oracle for testing, hardcode to $2.5/token.

app/components/disconnected-warning.tsx, package-lock.json
https://app.asana.com/0/home/1201981678382625/1202132817046459
=> POC add or switch network

app/components/fi-modal/borrow-balance.tsx, app/components/fi-modal/borrow-limit.tsx
Ref: https://app.asana.com/0/1202286057283894/1202295833967746
=> No NaN for fresh wallet

app/hooks/use-valid-input.ts
https://app.asana.com/0/1202286057283894/1202295833967775
=> Checks if value is coerced

app/components/account-summary.tsx
Ref: https://app.asana.com/0/1202286057283894/1202295833967758
=> Explicitly check for nullish

app/components/two-panes.tsx, app/hooks/use-network-to-blockchain-explorer.ts
https://app.asana.com/0/1202286057283894/1202314887500223
=> Don’t show empty tables when no coins supplied / borrowed

app/components/account-summary/ring.tsx
https://app.asana.com/0/1202286057283894/1202286100788829
=> Negative stroke color + animation

app/components/borrow-flow/borrow.tsx, app/components/borrow-flow/repay.tsx, app/hooks/use-markets.ts, app/hooks/use-max-borrow-amount.ts, app/hooks/use-new-total-borrowed-amount-in-usd.ts, app/hooks/use-safe-max-borrow-amount-for-token.ts, app/hooks/use-tender-context.ts, app/hooks/use-token-pairs.ts, app/lib/apy-calculations.ts, app/lib/tender.ts, app/types/global.ts
Move price onto token and calculate it once when creating the token pairs so we don’t have to re-calculate it a bunch of times
=> Price lookup refactor

app/hooks/use-valid-input.ts
Ref: https://app.asana.com/0/1202286057283894/1202356805925141
=> Zero pad incoming values when value starts with a dot

app/components/borrow-flow/borrow.tsx, app/components/borrow-flow/repay.tsx, app/components/deposit-flow/deposit.tsx, app/components/deposit-flow/withdraw.tsx
=> Text legibility on disabled state

app/hooks/use-valid-input.ts
=> Fixes lint error when redefining value

app/config/networks/rinkeby.ts
Removing to keep QA possible on rinkeby
=> Odd supplyRatePerBlock contract error on only the bat token on rinkeby

app/components/borrow-flow/borrow.tsx, app/components/borrow-flow/repay.tsx, app/components/deposit-flow/deposit.tsx, app/components/deposit-flow/withdraw.tsx
Ref: https://app.asana.com/0/1202286057283894/1202377650434278
=> Close modal if there is an error

app/components/two-panes.tsx
=> Add liquidity to borrow pane

app/components/two-panes.tsx, app/lib/tender.ts, app/types/human-readable-numbers.d.ts, package-lock.json, package.json
=> Shows small and large numbers better

.storybook/main.js, app/components/account-summary/display.tsx, app/components/borrow-flow/borrow.tsx, app/components/borrow-flow/repay.tsx, app/components/deposit-flow/deposit.tsx, app/components/deposit-flow/withdraw.tsx, app/components/fi-modal/borrow-balance.tsx, app/components/fi-modal/borrow-limit.tsx, app/components/max.tsx, app/lib/ui.ts, package-lock.json, package.json, stories/Button.stories.tsx, stories/Header.stories.tsx, stories/Page.stories.tsx, stories/app/components/account-summary/display.stories.tsx, stories/app/components/borrow-flow/borrow.stories.tsx, stories/app/components/borrow-flow/repay.stories.tsx, stories/app/components/deposit-flow/deposit.stories.tsx, stories/app/components/deposit-flow/withdraw.stories.tsx
@johnmosesman formatting in all modals. Moving onto panes next.
=> Format numbers in modals

app/hooks/use-valid-input.ts
=> Removes trailing zero if used in value validation

app/components/two-panes.tsx, app/lib/ui.ts
=> Adds other currency to all markets

app/components/connect-wallet.tsx
=> Detect if no metamask

app/components/deposit-flow/deposit.tsx, app/components/deposit-flow/withdraw.tsx, app/components/token-page/tokenChart.tsx, app/components/token-page/tokenMarketDetails.tsx, app/components/token-page/tokenTopDetailsBorrow.tsx, app/components/token-page/tokenTopDetailsSupply.tsx, app/hooks/use-collateral-factor.ts, app/hooks/use-market-info.ts, app/lib/tender.ts
* Fix name of GLP and tGLP tokens
* Add max LTV value to deposit modal
* Fix max LTV value on token page
=> [Fix] Fix GLP token and add max LTV value

app/components/borrow-flow/borrow.tsx, app/components/borrow-flow/repay.tsx
- Borrow Apy data is positive, while displaying show as negative percentage
=> [Fix]  Set borrow apy as negative

app/components/token-page/Token.tsx, app/components/token-page/tokenInterestRate.tsx, app/components/token-page/tokenTopDetails.tsx, app/hooks/use-market-info.ts
- remove borrow line from chart
- remove borrow apy and total borrow sections from top
=> remove borrow apy from glp market page

app/config/networks/arbitrum.ts, app/hooks/use-gmx-apy.ts
* Fix error when GMX is disabled
* Change sort order of GLP and GMX
* Disable GMX
=> [Release] Deploy v23.1.4.1454

app/components/deposit-borrow-flow/GlpCooldownTimer.tsx, app/components/deposit-borrow-flow/withdraw.tsx, app/components/earn-page/Vault.tsx, app/components/earn-page/earnContent.tsx, app/components/earn-page/modal.tsx, app/config/networks/arbitrum.ts, app/hooks/use-glp-cooldown.ts, app/hooks/use-web3-signer.ts, app/lib/tnd.ts, app/routes/api/circulating_supply.ts, app/types/global.ts, eth-sdk/config.ts
Includes #250 + address updates
=> Vesting addresses
